### PR TITLE
Add "Open in Veekun" option

### PR DESCRIPTION
**Pull request by magical**
What it says on the tin.

### CODE REVIEW

**Review by mwyoung — APPROVED** [review]

**Comment by hammockt** [comment]
For getBulbapediaPage() and getVeekunUrl(), should we be keeping those in PokeAPIUtils? They do operate on Pokemon resource names but they don't really interact with PokeAPI

**Comment by magical** [comment]
Probably not. They're easy to move though, since they're static.

**Comment by hammockt** [comment]
I feel like giving them their own class would be overkill, but maybe we could include them in the view code where they are used (since that is where they are relevant). Assuming they aren't really reused throughout the code.

**Comment by magical** [comment]
Done.

**Pull request merged**
