### PR TITLE
Add type icon assets, and some example code which displays them

### PR DESCRIPTION
**Pull request by magical**

### CODE REVIEW

**Review by mwyoung — APPROVED** [review]
This code looks fine to me. Would this tab be for only showing the types, or something else?
I also have code to show the type matchups and what each move type is, which would probably require adding some of this code to that instead of the current text (branch PokeDetails).

**Comment by magical** [comment]
@mwyoung I was imagining that it would be the type report (i don't think we need a plain list of types), but  we can move it around if we want — I saw that your mockup has the type report as a separate activity instead of a tab. Feel free to just grab the icon rendering code from TypeReportFragment and then delete the class.

**Comment by mwyoung** [comment]
I was thinking it would be a separate activity due to the fact that each team should have a separate version of each report (if we do have multiple teams).

**Comment by hammockt** [comment]
LGTM minus the hardcoded strings, but that can be refactored away later when we have a better idea of how this will interact the view code

**Comment by magical** [comment]
Yeah, the view code wasn't meant to be permanent. I'll merge this so we can start playing with the icons.

**Pull request merged**
