### PR TITLE
Error msg

### PR DESCRIPTION
**Pull request by mwyoung**
I updated several files including the MainActivity and activity_main.
The changes for PokeAPIViewModel (and Status) mostly came from assignment-4 and trying to get some of those features in. If needed we could always delete these changes and make it back to how it originally functioned. 

The major changes is now when there is no internet connection there is a red warning that states this fact.

### CODE REVIEW

**Comment by magical** [comment]
Per discussion, we probably don't need the explicit loading status variable.

**Comment by mwyoung** [comment]
The status variable has been removed, and this should be able to be merged.

**Review by magical — APPROVED** [review]
LGTM

**Comment by hammockt** [comment]
LGTM

**Review by hammockt — APPROVED** [review]

**Pull request merged**
