### PR TITLE
Live data list 2.0

### PR DESCRIPTION
**Pull request by hammockt**
This introduces changes to the live data list that you guys will eventually need for the upcoming features. The three big changes that happened for this where adding post creation, sorting, and general code cleanup.

Adding post creation: you can now add live data objects post creation to be managed by the list. Should come in handy for the team view when you guys implement adding Pokemon to a given team

Sorting: sorting is now supported and works by passing in a comparator of the type that the live data objects are observing. Basically if you have a LiveDataList<Pokemon>, then you could pass in a custom sort function for Pokemon and the list will rearrange itself and its observers. Should come in handy if you guys implement sorting for the list views.

Code cleanup: new code is a lot cleaner, requires no more garbage collection maintenance, and no longer needs a LifecycleOwner as a dependency. Removing the lifecycle dependency was mainly a design choice, because hypothetically the LiveDataList object could be passed and used in multiple activities/fragments (making it a lot more flexible). This is the part that I would really like to test more but #12 would make it a lot easier

### CODE REVIEW

**Review by mwyoung — APPROVED** [review]
Looks good to me.
I feel that #12 is also ready to be added. So if you want to first add that one and then both #13 and #14 I am OK with that.

**Comment by mwyoung** [comment]
I have merged in #12, so this branch should be ready for testing.

**Comment by hammockt** [comment]
@mwyoung @magical 

I was able to test it and I did find a bug. My solution uses a MediatorLiveData object that can observe and fire observable events based on other LiveData objects. The problem is that LiveData observering only works when the MediatorLiveData object has a least one active observer on it (who would have thought?). This has been fixed and should perform identically like before.

Also remember in class when I said that in a multi-activity application our ViewModel's cached data could spontaneously disappear? Well one of my tests was able to replicate that. Looks like we are going to need a repository that stores the data, where our ViewModels request/grab from that. I was originally planning on tackling that later, but I will definitely tackle that next since we were probably going to start loading resources into the application very soon.

**Comment by mwyoung** [comment]
Nice find and fix on the bug. If you feel like this code is ready to be merged I am fine with that.

**Pull request merged**
