### PR TITLE
Poke api repository

### PR DESCRIPTION
**Pull request by hammockt**
This is rather big change that implements the repository, hooks up the priority networking (which automatically loads our resources in the background now), and saves the RateLimiter's state (to take into account the rate of previous instances of the app). Probably should have done the last two in separate pull requests, but I hooked them up early on and was forced to stick to my decision.

The repository now is a global resource that lives throughout the entire life our application. Before with the view model, the data lived until the view model was destroyed (going into another activity). Which would cause loaded Pokemon resources to disappear if you went from one activity to the next. Which is fixed by this.

Priority Networking is now hooked up to the repository and resources are loaded automatically in the background based on their dependencies and their priority. I should have explained this better in the past, but I didn't exactly do the best job of explaining what was loaded at a given time. The resources will start getting loaded when the repository is statically init, which is basically when the first class uses the repository (the first view model ever created by the application). Next the type list -> move list -> Pokemon list are loaded. When a list loads, it contains all of the deferred resources that point to where the data is really loaded. This means that you guys can start interacting with those references as long as you can get away with the id and the name. Next the individual deferred resources will start loading when on their dependencies have finished loading. Types have no dependencies, moves depend on the type list, and Pokemon depend on the type/move list. One thing to note is that they do not depend on the fully loaded resources that come later, only the deferred ones. They can get away with this because they internally store those references as live data. Once the dependencies have been met, they will then be enqueued to be fully loaded into the application.

The RateLimiter is also much smarter now where it keeps track of the rate of the last application close. It takes this into account at init and helps deal with that one bug where if 100 requests were kicked off and one immediately closed/re-opened the application. This is done with a shared preference at application start (even before the main activity starts).

### CODE REVIEW

**Review by mwyoung — APPROVED** [review]
I don't have a problem with any of this code. I also want to understand the code for PokemonItemDetailActivity where it first makes sure the list is not null and then requests a Pokemon. Since that Pokemon has not been loaded yet would it only return information that was from the list of Pokemon (ID/Name) and request a download of the Pokemon, or something else?

**Comment by hammockt** [comment]
@mwyoung that is correct. However as of right now, the loading of Pokemon is not driven by the UI. If you were to retrieve a Pokemon from the list in the view code, there are currently no hints passed to the view model and the repository that the Pokemon should be loaded immediately. The code for it is there and could be hooked up but I haven't done so because it is prone to unintended consequences. An example of this could be fully loading Bulbasaur when they go to the PokemonItemDetailActivity. When the view retrieves him from the cache do we need all of this data? Do we need to show his types? Do we need to show all of this 88 moves? Unfortunately different views could need certain resources more or less loaded than others. Applying a one fits all approach to that could work for some, be overkill for some others, and insufficient for a few. I have an idea of this can handled but that is for later

**Comment by mwyoung** [comment]
@hammockt Alright. As long as you have a plan, I am fine with it.

**Review by magical — APPROVED** [review]
LGTM

**Pull request merged**
