### PR TITLE
First README update, small bug fixes

### PR DESCRIPTION
**Pull request by mwyoung**
Small updates due to crashes/FAB bug from Google, adding a gif
WalkthroughTeamBuilder

### CODE REVIEW

**Comment by magical** [comment]
Looks good. Not sure what you mean by a "google bug" though.

**Comment by mwyoung** [comment]
There is a bug with the FAB when changing colors where the icon can disappear. https://stackoverflow.com/questions/51919865/disappearing-fab-icon-on-navigation-fragment-change and https://issuetracker.google.com/issues/117476935 has the details.

**Comment by mwyoung** [comment]
If you both are OK with these changes I was going to merge tomorrow morning. If not, let me know.

**Comment by hammockt** [comment]
LGTM

**Pull request merged**
