### PR TITLE
Some code structuring

### PR DESCRIPTION
**Pull request by hammockt**
Since we have like 20+ files, we should probably start organizing the code a wee bit more. This pull request structures the code into 3 main packages which represent all of the components in our architecture. The 3 components are the Model, View, and ViewModel (because for now we are a MVVM application). Unfortunately when I was putting code into their sub-packages, things had to be made public. And you can only have one public class for a given file, so package-private classes that were amassed in one file had to be split up.

While I was at it I also ran Android Studio's "Reformat" code and "Optimize Imports". Most of the code changes come from running those two commands, but at least all of the files are now consistent.

### CODE REVIEW

**Review by mwyoung — APPROVED** [review]

**Comment by magical** [comment]
Aren't package names usually all lowercase?

**Comment by hammockt** [comment]
@magical

Fixed

**Comment by magical** [comment]
Excellent.

SGTM. Can't wait to fix all the merge commits this will create.

**Comment by hammockt** [comment]
Its not my fault if the Git Gods hate thy

**Pull request merged**
